/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUpgradeable__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "MyDate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MyDate__factory>;
    getContractFactory(
      name: "TokenAvgPrice1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenAvgPrice1__factory>;
    getContractFactory(
      name: "TokenAvgPrice2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenAvgPrice2__factory>;
    getContractFactory(
      name: "TokenAvgPrice3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenAvgPrice3__factory>;

    getContractAt(
      name: "OwnableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableUpgradeable>;
    getContractAt(
      name: "Pausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "MyDate",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MyDate>;
    getContractAt(
      name: "TokenAvgPrice1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenAvgPrice1>;
    getContractAt(
      name: "TokenAvgPrice2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenAvgPrice2>;
    getContractAt(
      name: "TokenAvgPrice3",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenAvgPrice3>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
